In [1]:
from __future__ import print_function
import torch

## Tensors

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-36 *
       [[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0062,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 3.0643,  0.0000,  0.0000]])


In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[ 0.0801,  0.3143,  0.4888],
        [ 0.5566,  0.7247,  0.7228],
        [ 0.5060,  0.6665,  0.5926],
        [ 0.3706,  0.6689,  0.1219],
        [ 0.6303,  0.4616,  0.3128]])


In [4]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [6]:
# Create a tensor basing on existing tensor. 
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.4934,  0.5666,  0.5751],
        [-1.6903,  0.1445,  0.6767],
        [ 0.1864, -0.7772,  0.4779],
        [-0.7120,  1.3420,  0.8621],
        [-0.2666, -1.3353,  0.1584]])


In [7]:
# Get its size
print(x.size())

torch.Size([5, 3])


**Note:** `torch.Size` is in fact a tuple, so it supports all tuple operations.

## Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

**Addition:** syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5282,  1.4142,  1.3892],
        [-1.4279,  0.4807,  0.8634],
        [ 1.0171,  0.1987,  0.8188],
        [-0.3374,  1.3463,  1.5170],
        [ 0.0879, -0.6052,  0.5646]])


**Addition:** syntax 2

In [9]:
print(torch.add(x, y))

tensor([[-0.5282,  1.4142,  1.3892],
        [-1.4279,  0.4807,  0.8634],
        [ 1.0171,  0.1987,  0.8188],
        [-0.3374,  1.3463,  1.5170],
        [ 0.0879, -0.6052,  0.5646]])


**Addition:** providing an output tensor as argument

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5282,  1.4142,  1.3892],
        [-1.4279,  0.4807,  0.8634],
        [ 1.0171,  0.1987,  0.8188],
        [-0.3374,  1.3463,  1.5170],
        [ 0.0879, -0.6052,  0.5646]])


**Addition:** in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5282,  1.4142,  1.3892],
        [-1.4279,  0.4807,  0.8634],
        [ 1.0171,  0.1987,  0.8188],
        [-0.3374,  1.3463,  1.5170],
        [ 0.0879, -0.6052,  0.5646]])


**Note:** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([ 0.5666,  0.1445, -0.7772,  1.3420, -1.3353])


**Resizing:** If you want to resize/reshape tensor, you can use `torch.view`:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor(1.00000e-02 *
       [-2.0223])
-0.020223375409841537


100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [16]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [17]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


In [20]:
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back

### CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!